version: '3.3'

services:

  feedgordon:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend

  mongo:
    image: mongo:latest
    networks:
      - backend
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: AbobNebCoodVia7
    ports:
      - "27017:27017"

volumes:
  mongo-data:

networks:
  frontend:
  backend:
