version: '3.3'

secrets:
  password:
    file: ./password

services:

  feedgordon:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend

  mongo:
    image: mongo:latest
    networks:
      - backend
    restart: always
    secrets:
      - password
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: AbobNebCoodVia7

volumes:
  mongo-data:

networks:
  frontend:
  backend:


